### ISSUE TITLE
Running Akmai cli on CI pipeline

### ISSUE THREAD

**Issue by consbish** [akamai/cli#150]
We are running the below command to run on GitHub runner.
akamai install purge
But it is asking for user prompt (Y/N) to install the purge & it fails as we can ask enter prompt (Y/N) in a pipeline as it use bash shell.
Could you please help me to resolve this issue ?

**Comment by robertolopezlopez** [comment]
Hi @consbish ,

Thank you for this report.

This is a [known issue which has previously been reported](https://github.com/akamai/cli/issues/136) and already fixed in our internal repository. It will be released soon.

Given the duplication, I will close this issue and encourage you to follow the other.

Kind regards,

Roberto
